export const POL_FORM_FIELDS = {
  acquisitionMethod: 'acquisitionMethod',
  automaticExport: 'automaticExport',
  cancellationRestriction: 'cancellationRestriction',
  cancellationRestrictionNote: 'cancellationRestrictionNote',
  checkinItems: 'checkinItems',
  claimingActive: 'claimingActive',
  claimingInterval: 'claimingInterval',
  collection: 'collection',
  contributors: 'contributors',
  costListUnitPrice: 'cost.listUnitPrice',
  costListUnitPriceElectronic: 'cost.listUnitPriceElectronic',
  costQuantityElectronic: 'cost.quantityElectronic',
  costQuantityPhysical: 'cost.quantityPhysical',
  details: 'details',
  donor_DEPRECATED: 'donor',
  donorOrganizationIds: 'donorOrganizationIds',
  edition: 'edition',
  eresource: 'eresource',
  eresourceActivationDue: 'eresource.activationDue',
  eresourceCreateInventory: 'eresource.createInventory',
  fundDistribution: 'fundDistribution',
  instanceId: 'instanceId',
  isBinderyActive: 'details.isBinderyActive',
  isPackage: 'isPackage',
  locations: 'locations',
  orderFormat: 'orderFormat',
  packagePoLineId: 'packagePoLineId',
  paymentStatus: 'paymentStatus',
  physical: 'physical',
  physicalCreateInventory: 'physical.createInventory',
  poLineDescription: 'poLineDescription',
  publicationDate: 'publicationDate',
  publisher: 'publisher',
  receiptDate: 'receiptDate',
  receiptStatus: 'receiptStatus',
  requester: 'requester',
  rush: 'rush',
  selector: 'selector',
  tagsList: 'tags.tagList',
  titleOrPackage: 'titleOrPackage',
};

export const PO_LINE_FORM_FIELD_ARRAYS_TO_HYDRATE = [POL_FORM_FIELDS.locations];
