export const POL_FORM_FIELDS = {
  checkinItems: 'checkinItems',
  contributors: 'contributors',
  costListUnitPrice: 'cost.listUnitPrice',
  costListUnitPriceElectronic: 'cost.listUnitPriceElectronic',
  costQuantityElectronic: 'cost.quantityElectronic',
  costQuantityPhysical: 'cost.quantityPhysical',
  details: 'details',
  donorOrganizationIds: 'donorOrganizationIds',
  edition: 'edition',
  eresource: 'eresource',
  eresourceActivationDue: 'eresource.activationDue',
  eresourceCreateInventory: 'eresource.createInventory',
  fundDistribution: 'fundDistribution',
  instanceId: 'instanceId',
  isBinderyActive: 'details.isBinderyActive',
  isPackage: 'isPackage',
  locations: 'locations',
  orderFormat: 'orderFormat',
  packagePoLineId: 'packagePoLineId',
  physical: 'physical',
  physicalCreateInventory: 'physical.createInventory',
  publicationDate: 'publicationDate',
  publisher: 'publisher',
  receiptStatus: 'receiptStatus',
  titleOrPackage: 'titleOrPackage',
};
